// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://efhunjwanllwehqivlfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmaHVuandhbmxsd2VocWl2bGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MTYyNzAsImV4cCI6MjA4NzM5MjI3MH0.BHo0yg_oJ-9ESdwpWZGZoU72oqKOHB2eYPOD0gGZ3r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);